<?php
	echo 'Hello world'.'<br>';
	echo '<a href="block2\lessons1\lessons1.php">block2_lessons1</a>';
	echo '<br>';
	echo '<a href="block2\lessons2\lessons2.php">block2_lessons2</a>';
	echo '<br>';
	echo '<a href="block2\lessons3\lessons3.php">block2_lessons3</a>';
	echo '<br>';
	echo '<a href="block2\lessons4\lessons4.php">block2_lessons4</a>';
	echo '<br>';
	echo '<a href="block2\lessons5\lessons5.php">block2_lessons5</a>';
	echo '<br>';
	echo '<a href="block2\lessons6\lessons6.php">block2_lessons6</a>';
	echo '<br>';
	echo '<a href="block2\lessons7\lessons7.php">block2_lessons7</a>';
	echo '<br>';
	echo '<a href="block2\lessons8\lessons8.php">block2_lessons8</a>';
	echo '<br>';
	echo '<a href="block2\lessons9\lessons9.php">block2_lessons9</a>';
	echo '<br>';
	echo '<a href="block2\lessons10\lessons10.php">block2_lessons10</a>';
	echo '<br>';
	echo '<a href="block3\lessons1.php">block3_lessons1</a>';
	echo '<br>';
	echo '<a href="block3\lessons2.php">block3_lessons2</a>';
	echo '<br>';
	echo '<a href="block3\lessons3.php">block3_lessons3</a>';
	echo '<br>';
	echo '<a href="block3\lessons4.php">block3_lessons4</a>';
	echo '<br>';
	echo '<a href="block3\lessons5\lessons5.1.php">block3_lessons5.1</a>';
	echo '<br>';
	echo '<a href="block3\lessons5\lessons5.3.php">block3_lessons5.3</a>';
	echo '<br>';
	echo '<a href="block3\lessons5\lessons5.4.php">block3_lessons5.4</a>';
	echo '<br>';
	echo '<a href="block3\lessons5\lessons5.5.php">block3_lessons5.5</a>';
	echo '<br>';
	echo '<a href="block3\lessons5\lessons5.6.php">block3_lessons5.6</a>';
	echo '<br>';
	echo '<a href="block3\lessons5\lessons5.7\lessons5.7.php">block3_lessons5.7</a>';
	echo '<br>';
	echo '<a href="block4\lessons1.php">block4_lessons1</a>';
	echo '<br>';
	echo '<a href="block4\lessons2.php">block4_lessons2</a>';
	echo '<br>';
	echo '<a href="block4\lessons3.php">block4_lessons3</a>';
	echo '<br>';
?>
